# Overall Filter Parameters

gui_publish_rate: 10.0 
min_particles: 500 
max_particles: 5000 
kld_err: 0.05 
kld_z: 0.99 
update_min_d: 0.1 
update_min_a: 0.1
resample_interval: 2 
transform_tolerance: 0.5   

# Laser Scanner Model Parameters
laser_z_hit: 0.5 
laser_z_short: 0.05 
laser_z_max: 0.05 
laser_z_rand: 0.5 
laser_sigma_hit: 0.2 
laser_lambda_short: 0.1 
laser_lambda_short: 0.1 
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field 

# Odometry Model Paramters
odom_model_type: diff 
odom_alpha1: 0.2 
odom_alpha2: 0.2 
odom_alpha3: 0.2 
odom_alpha4: 0.2 
base_frame_id: base_link
odom_frame_id: odom 
global_frame_id: map
 

