global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0 #before: 5.0
  publish_frequency: 2 #before 0.5
  static_map: true
  # rolling_window: true
  transform_tolerance: 0.5
  cost_scaling_factor: 1
  inflation_radius: .1
  width: 30
  height: 30
  plugins:
    - {name: static_map_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
    - {name: 2d_obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: 3d_obstacles_layer,  type: "costmap_2d::VoxelLayer"}
    # - {name: rgbd_obstacle_layer,     type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}

